asgard/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path("", views.index, name="index"),
    path("contact-page", views.contact, name="contact"),
    path("about-us", views.about, name="about"),
    path("rooms", views.rooms, name="rooms"),
    path("room/<int:id>/<str:name>", views.room, name="room"),
    path("available", views.available, name="available"),
    path("reservation/<int:id>/<str:name>", views.reservation, name="reservation"),
    path("reservation_submit/<int:id>/<str:status>", views.reservation_submit, name="reservation_submit"),
    path('checkout/<int:id>', views.checkout, name='checkout'),
    path('confirmation/<str:status>', views.confirmation, name='confirmation'),
    # API/AJAX
    path("reservatoindata/<int:id>", views.reservatoindata, name="reservatoindata"),
    path("roomdata/<int:id>", views.roomdata, name="roomdata"),
]

hotel/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("asgard.urls")),
]

asgard/models.py
from django.db import models


class Rooms(models.Model):
    class Meta:
        verbose_name_plural = 'Rooms'

    room_name = models.CharField(max_length=64)
    bed_type = models.CharField(max_length=64)
    max_people = models.IntegerField()
    accommodates = models.IntegerField()
    bathrooms = models.IntegerField()
    bedroom = models.IntegerField()
    beds = models.IntegerField()
    view = models.CharField(max_length=32)
    adult_price = models.DecimalField(max_digits=7, decimal_places=2)
    child_price = models.DecimalField(max_digits=7, decimal_places=2)
    weekly_discount = models.IntegerField()
    url_slug = models.CharField(max_length=64)

    def __str__(self):
        return self.room_name

    def room_api(self):
        return {
            'room_id': self.id,
            'adult_price': self.adult_price,
            'child_price': self.child_price,
            'weekly_discount': self.weekly_discount,
        }


class Media(models.Model):
    class Meta:
        verbose_name_plural = 'Media'

    room_name = models.ForeignKey(Rooms, on_delete=models.CASCADE)
    image_main = models.CharField(max_length=256, default='-')
    image_1 = models.CharField(max_length=256, default='-')
    image_2 = models.CharField(max_length=256, default='-')
    image_3 = models.CharField(max_length=256, default='-')
    image_4 = models.CharField(max_length=256, default='-')
    image_5 = models.CharField(max_length=256, default='-')

    def __str__(self):
        return self.room_name.room_name



class Reservations(models.Model):
    class Meta:
        verbose_name_plural = 'Reservations'

    reserved_room = models.ForeignKey(Rooms, on_delete=models.CASCADE)
    first_name = models.CharField(max_length=64)
    last_name = models.CharField(max_length=64)
    email = models.CharField(max_length=64)
    phone = models.CharField(max_length=64)
    address = models.CharField(max_length=64)
    address_2 = models.CharField(max_length=64, default='-')
    city = models.CharField(max_length=64)
    country = models.CharField(max_length=64)
    zipcode = models.CharField(max_length=64)
    price = models.DecimalField(max_digits=7, decimal_places=2)
    discount = models.DecimalField(max_digits=7, decimal_places=2, default=0)
    total = models.DecimalField(max_digits=7, decimal_places=2)
    vat = models.DecimalField(max_digits=7, decimal_places=2, default=8.0)
    grand_total = models.DecimalField(max_digits=7, decimal_places=2)
    adult = models.IntegerField(default=1)
    child = models.IntegerField(default=0)
    check_in = models.DateField(null=True)
    check_out = models.DateField(null=True)
    reservation_date = models.DateTimeField(auto_now=True)
    payed = models.BooleanField(default=False)

    def reservation_api(self):
        return {
            'room_id': self.reserved_room_id,
            'check_in': self.check_in,
            'check_out': self.check_out,
        }

    def __str__(self):
        return f"{self.last_name}, {self.first_name}, {self.check_in}, {self.check_out}, {self.reserved_room.room_name}, {self.reservation_date}"

asgard/views.py
from django.shortcuts import render
from django.conf import settings
from django.urls import reverse
from datetime import datetime
from .models import Rooms, Reservations
from django.http import JsonResponse
from django.views.decorators.csrf import csrf_exempt
from django.db.models import Q

import stripe
import json


stripe.api_key = settings.STRIPE_PRIVATE_KEY


# index page
def index(request):
    return render(request, "asgard/index.html")


# contact page
def contact(request):
    return render(request, "asgard/contact-page.html")


# about page
def about(request):
    return render(request, "asgard/about-us.html")


# Page for all rooms
def rooms(request):
    rooms = Rooms.objects.all()
    return render(request, "asgard/rooms.html", { 'rooms': rooms })


# Page for an individual room
def room(request, id, name):
    room = Rooms.objects.get(id=id)
    return render(request, "asgard/room.html", { 'room': room})


# Check available rooms at the index page
def available(request):
    if request.method == 'POST':
        checkin = request.POST['checkin']
        checkout = request.POST['checkout']
        adults = request.POST['adults']
        children = request.POST['children']
        totalPerson = int(adults) + int(children)

        # Add to sessions
        if "checkin" in request.session:
            del request.session["checkin"]
            request.session["checkin"] = request.POST['checkin']
        else:
            request.session["checkin"] = request.POST['checkin']

        if "checkout" in request.session:
            del request.session["checkout"]
            request.session["checkout"] = request.POST['checkout']
        else:
            request.session["checkout"] = request.POST['checkout']

        if "adults" in request.session:
            del request.session["adults"]
            request.session["adults"] = request.POST['adults']
        else:
            request.session["adults"] = request.POST['adults']

        if "children" in request.session:
            del request.session["children"]
            request.session["children"] = request.POST['children']
        else:
            request.session["children"] = request.POST['children']
            

        # Convert to datetime.date type
        checkin_date = datetime.strptime(checkin, "%Y-%m-%d").date()
        checkout_date = datetime.strptime(checkout, "%Y-%m-%d").date()

        # Check if the room is already reserved
        reservations = Reservations.objects.all()

        # Create excludes set list (Using set() to prevent duplications)
        excludes = set()
        # For loop for each reserved room
        for rooms in reservations:
            # Searching for the date range between the check-in and check-out dates which come through the form
            reserved = Reservations.objects.filter(Q(check_in__range=(checkin_date, checkout_date)) | Q(check_out__range=(checkin_date, checkout_date)))

            # If there is any reserved room
            if reserved.exists():
                # Loop through the reserved rooms
                for room in reserved:
                    # Append the reserved room-id to the excludes set list
                    excludes.add(room.reserved_room_id)
                    # With the exclude method, returned a new QuerySet with the available rooms (__in iterate the excludes set list)
                    available_rooms = Rooms.objects.exclude(id__in=excludes).filter(max_people__gte=totalPerson)

            else:
                available_rooms = Rooms.objects.all().filter(max_people__gte=totalPerson)
                return render(request, "asgard/rooms.html", {'rooms': available_rooms})

    return render(request, "asgard/rooms.html", {'rooms': available_rooms})


# Save the pre-reservation form's input values into session at the room page
def reservation(request, id, name):
    room = Rooms.objects.get(id=id)

    if request.method == 'POST':
        # Add to sessions
        if "checkin" in request.session:
            del request.session["checkin"]
            request.session["checkin"] = request.POST['checkin']
        else:
            request.session["checkin"] = request.POST['checkin']

        if "checkout" in request.session:
            del request.session["checkout"]
            request.session["checkout"] = request.POST['checkout']
        else:
            request.session["checkout"] = request.POST['checkout']

        if "adults" in request.session:
            del request.session["adults"]
            request.session["adults"] = request.POST['adults']
        else:
            request.session["adults"] = request.POST['adults']

        if "children" in request.session:
            del request.session["children"]
            request.session["children"] = request.POST['children']
        else:
            request.session["children"] = request.POST['children']

    return render(request, "asgard/reservation.html", { 'room': room })


# For JS to fetch the prices and make calculations
def reservatoindata(request, id):
    reservations = Reservations.objects.filter(reserved_room_id=id)
    return JsonResponse([reservation.reservation_api() for reservation in reservations], safe=False)


# For JS to fetch the prices and make calculations
def roomdata(request, id):
    room = Rooms.objects.get(id=id)
    return JsonResponse(room.room_api())


# Submit the reservation, and add to the database either paid or unpayed
@csrf_exempt
def reservation_submit(request, id, status):
    room = Rooms.objects.get(id=id)
    adults = request.session["adults"]
    children = request.session["children"]
    checkin = datetime.strptime(request.session["checkin"], '%Y-%m-%d').date()
    checkout = datetime.strptime(request.session["checkout"], '%Y-%m-%d').date()
    adult_price = room.adult_price
    child_price = room.child_price
    discount = 0

    differenceInTime = checkout - checkin
    days = differenceInTime.days

    subtotal = ((float(adult_price) * float(adults)) + (float(child_price) * float(children))) * float(days)
    if days >= 7:
        discount = subtotal * 0.15
    total = subtotal - discount
    vat = total * 0.08
    # Float with 2 decimals
    grandtotal = format(total + vat, '.2f')

    # Check if the room is already reserved
    reservations = Reservations.objects.all()

    # For loop for each reserved room
    for rooms in reservations:
        # Searching for the date range between the check-in and check-out dates which come through the form
        reserved = Reservations.objects.filter(reserved_room_id=id).filter(check_in__range=(checkin, checkout)) | Reservations.objects.filter(reserved_room_id=id).filter(check_out__range=(checkin, checkout))

    if reserved.exists():
        return render(request, "asgard/confirmation.html", { 'message': 'Error' })
    else:
        if request.method == 'POST':
            if status == 'unpayed':
                reservation = Reservations()
                reservation.reserved_room_id = id
                reservation.first_name = request.POST["first-name"]
                reservation.last_name = request.POST["last-name"]
                reservation.email = request.POST["email"]
                reservation.phone = request.POST["phone"]
                reservation.address = request.POST["address"]
                reservation.address_2 = request.POST["address2"]
                reservation.city = request.POST["city"]
                reservation.country = request.POST["country"]
                reservation.zipcode = request.POST["zipcode"]
                reservation.price = subtotal
                reservation.discount = discount
                reservation.total = total
                reservation.vat = vat
                reservation.grand_total = grandtotal
                reservation.adult = adults
                reservation.child = children
                reservation.check_in = checkin
                reservation.check_out = checkout
                reservation.payed = False
                reservation.save()           

                return render(request, "asgard/confirmation.html", { 'message': 'Success' })

            # After successfull card payment JS fetch post request at the comfirmation page
            if status == 'payed':
                data = json.loads(request.body)
                reservation = Reservations()
                reservation.reserved_room_id = id
                reservation.first_name = data.get('firstName', '')
                reservation.last_name = data.get('lastName', '')
                reservation.email = data.get('email', '')
                reservation.phone = data.get('phone', '')
                reservation.address = data.get('address', '')
                reservation.address_2 = data.get('address2', '')
                reservation.city = data.get('city', '')
                reservation.country = data.get('country', '')
                reservation.zipcode = data.get('zip', '')
                reservation.price = subtotal
                reservation.discount = discount
                reservation.total = total
                reservation.vat = vat
                reservation.grand_total = grandtotal
                reservation.adult = adults
                reservation.child = children
                reservation.check_in = checkin
                reservation.check_out = checkout
                reservation.payed = True
                reservation.save()  

        else:
            return render(request, "asgard/confirmation.html", { 'message': 'SuccesPayment' })
 
    return render(request, "asgard/confirmation.html", { 'message': 'Error' })


# Stripe card payment
def checkout(request, id):
    room = Rooms.objects.get(id=id)
    adults = request.session["adults"]
    children = request.session["children"]
    checkin = datetime.strptime(request.session["checkin"], '%Y-%m-%d').date()
    checkout = datetime.strptime(request.session["checkout"], '%Y-%m-%d').date()

asgard/templates/asgard/about-us.html
{% extends "asgard/layout.html" %}
{% load static %}
{% block body %}

<section class="">
    <div class="py-5 aboutus-header">
        <h1 class="m-0 px-3 text-center">About Us</h1>
    </div>

    <div class="row px-3 mx-0 my-5 about">
        <div class="col-md-4">
            <h1>Tortor Tellus Cras</h1>
            <div class="aboutus-divider mb-4"></div>
            <p>
                Aenean lacinia bibendum nulla sed consectetur. Fusce dapibus, tellus ac cursus commodo, tortor mauris condi mentum nibh.
            </p>
        </div>
        <div class="col-md-4">
            <h1>Dolor Fusce Ligula</h1>
            <div class="aboutus-divider mb-4"></div>
            <p>
                Aenean lacinia bibendum nulla sed consectetur. Fusce dapibus, tellus ac cursus commodo, tortor mauris condi mentum nibh.
            </p>
        </div>
        <div class="col-md-4">
            <h1>Inceptos Dolor Mollis</h1>
            <div class="aboutus-divider mb-4"></div>
            <p>
                Aenean lacinia bibendum nulla sed consectetur. Fusce dapibus, tellus ac cursus commodo, tortor mauris condi mentum nibh.
            </p>
        </div>

        <div class="col-md-12 my-4 text-center">
            <h1 style="font-size: 27px;">Commodo Tellus</h1>
            <div class="col-12 mb-4 text-center aboutus-divider-middle"></div>
        </div>
        

        <div class="col-md-4 d-flex aboutus-bottom-container">
            <img src="{% static 'asgard/img/aboutus01.jpg' %}" alt="About Us" class="aboutus-img">
        </div>
        <div class="col-md-8 mt-5 ps-3 aboutus-bottom-container">
            <div class="mb-4">
                <h1>Condimentum Porta Aenean <i class="fas fa-redo-alt ps-3 font-icon"></i></h1>
                <p>
                    Cras justo odio, dapibus ac facilisis in, egestas eget quam. Integer posuere erat a ante venenatis dapibus posuere velit aliquet. Praesent commodo cursus magna, vel scelerisque nisl consectetur et. Cum sociis natoque penatibus et magnis dis parturient montes.
                </p>
            </div>
            <div class="mb-4">
                <h1>Etiam Justo Ullamcorper <i class="fas fa-circle-notch ps-3 font-icon"></i></h1>
                <p>
                    Cras justo odio, dapibus ac facilisis in, egestas eget quam. Integer posuere erat a ante venenatis dapibus posuere velit aliquet. Praesent commodo cursus magna, vel scelerisque nisl consectetur et. Cum sociis natoque penatibus et magnis dis parturient montes.
                </p>
            </div>
            <div class="mb-4">
                <h1>Inceptos Vulputate Fusce <i class="far fa-heart ps-3 font-icon"></i></h1>
                <p>
                    Cras justo odio, dapibus ac facilisis in, egestas eget quam. Integer posuere erat a ante venenatis dapibus posuere velit aliquet. Praesent commodo cursus magna, vel scelerisque nisl consectetur et. Cum sociis natoque penatibus et magnis dis parturient montes.
                </p>
            </div>
            <div>
                <h1>Dapibus Mattis Parturient <i class="far fa-star ps-3 font-icon"></i></h1>
                <p>
                    Cras justo odio, dapibus ac facilisis in, egestas eget quam. Integer posuere erat a ante venenatis dapibus posuere velit aliquet. Praesent commodo cursus magna, vel scelerisque nisl consectetur et. Cum sociis natoque penatibus et magnis dis parturient montes.
                </p>
            </div>
        </div>
    </div>

</section>
{% endblock %}

asgard/templates/asgard/confirmation.html
{% extends "asgard/layout.html" %}
{% load static %}
{% block body %}

<section id="confirmation">
    <div class="py-5 custom-rooms-header">
        <h1 class="m-0 px-3 text-center">Room Selection</h1>
    </div>
    <div class="d-flex flex-wrap custom-rooms-main">
    {% if message == 'Success' %}        
        <div class="col-12 py-5 my-5 text-center alert alert-success" role="alert" style="padding: 6rem 0; margin: 10rem 0;">
            <h3>Reservation Completed!</h3>
            <h3>We have recieved your "Book now, Pay later" reservation.<br>
                We will conatct you shortly.<br>
                If you have any question, please don't hesitate to contact us.<br>
                Thank you!
            </h3>
        </div>
    {% elif message == 'SuccesPayment' %}  
        <div id="payed" class="col-12 py-5 my-5 text-center alert alert-success" role="alert" style="padding: 6rem 0; margin: 10rem 0;">
            <h3>Reservation Completed!</h3>
            <h3>We have recieved your reservation.<br>
                If you have any question, please don't hesitate to contact us.<br>
                Thank you!
            </h3>
        </div>
    {% elif message == 'Error' %}  
        <div class="col-12 py-5 my-5 text-center alert alert-danger" role="alert" style="padding: 6rem 0; margin: 10rem 0;">
            <h3>Something went wrong.<br>Please try again or contact us.</h3>
        </div>
    {% else %}
        <div class="col-12 py-5 my-5 text-center alert alert-danger" role="alert" style="padding: 6rem 0; margin: 10rem 0;">
            <h3>Something went wrong.<br>Please try again.</h3>
        </div>
    {% endif %}
    </div>

</section>

{% endblock %}

asgard/templates/asgard/contact-page.html
{% extends "asgard/layout.html" %}
{% load static %}
{% block body %}

<section class="">
    <div>
        <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3023.310125187248!2d-74.00894674802598!3d40.733201018377294!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x89c25993477ff92f%3A0x99a016bf79f4eeea!2s99%20Bedford%20St%2C%20New%20York%2C%20NY%2010014%2C%20USA!5e0!3m2!1sen!2suk!4v1627642689480!5m2!1sen!2suk" width="100%" height="450px" style="border:0;" allowfullscreen="" loading="lazy"></iframe>
    </div>
    <div class="row px-0 mx-2 my-5 custom-contact">
        <div class="col-md-6 mb-5">
            <form action="" method="post" id="" class="row g-3">
                {% csrf_token %}
                <div class="col-12">
                    <label for="inputName" class="form-label">Your Name</label>
                    <input type="text" name="name" class="form-control" id="inputName" maxlength="30" required>
                </div>
                <div class="col-12">
                    <label for="inputEmail" class="form-label">Your Email</label>
                    <input type="email" name="email" class="form-control" id="inputEmail" maxlength="50" required>
                </div>
                <div class="col-12">
                    <label for="inputMessage" class="form-label">Your Message</label>
                    <br>
                    <textarea rows="3" maxlength="150" wrap="hard"></textarea>
                </div>
                <div class="col-4 d-flex justify-content-center">
                    <button class="btn btn-outline-secondary px-5" data-bs-toggle="modal" data-bs-target="#modalmessage">Send</button>
                </div>
                <!-- Modal -->
                <div class="modal fade" id="modalmessage" tabindex="-1" aria-labelledby="modalmessageLabel"
                    aria-hidden="true">
                    <div class="modal-dialog">
                        <div class="modal-content">
                            <div class="modal-header">
                                <button type="button" class="btn-close" data-bs-dismiss="modal"
                                    aria-label="Close"></button>
                            </div>
                            <div class="modal-body text-center">
                                <p>Thank you for your message.<br>We will contact you shortly.</p>
                            </div>
                        </div>
                    </div>
                </div>
            </form>
        </div>

        <div class="col-md-6">
            <div class="px-2">
                <h1 class="mb-3">Before Contacting Us</h1>
                <p>
                    Lorem ipsum dolor sit amet, consectetur adipisici elit, sed eiusmod tempor incidunt ut labore et dolore magna aliqua. Non equidem invideo, miror magis posuere velit aliquet.
                </p>
            </div>
            <div class="mt-5 px-2">
                <h1 class="mb-3">Contact Information</h1>
                <ul class="list-unstyled">
                    <li><i class="fas fa-map-marker-alt"></i>&nbsp; 99 Bedford St, New York, NY 10014, USA</li>
                    <li><i class="fas fa-phone-alt"></i>&nbsp; 1600-555-6666</li>
                    <li><i class="far fa-envelope"></i>&nbsp; contact@hotelasgard.com</li>
                    <li><i class="far fa-clock"></i>&nbsp; Everyday 9:00-17:00</li>
                </ul>
            </div>

        </div>
    </div>
</section>

{% endblock %}

asgard/templates/asgard/layout.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <link href="{% static 'asgard/header.css' %}" rel="stylesheet">
    <link href="{% static 'asgard/home.css' %}" rel="stylesheet">
    <link href="{% static 'asgard/rooms.css' %}" rel="stylesheet">
    <link href="{% static 'asgard/room.css' %}" rel="stylesheet">
    <link href="{% static 'asgard/reservation.css' %}" rel="stylesheet">
    <link href="{% static 'asgard/contact.css' %}" rel="stylesheet">
    <link href="{% static 'asgard/aboutus.css' %}" rel="stylesheet">
    <link rel="icon"href="{% static 'asgard/favicon.ico' %}">
    <script src="https://kit.fontawesome.com/c2f64d8c0a.js" crossorigin="anonymous"></script>
    <title>{% block title %}Hotel Asgard{% endblock %}</title>
</head>
<body>
    <div class="container bg-white text-dark px-0">
        <header class="header">
            <nav class="navbar navbar-expand-lg navbar-light bg-light">
                <div class="container px-5">                    
                    <a class="navbar-brand" href="{% url 'index' %}"><img src="{% static 'asgard/img/asgard-hotel-logo.png' %}" alt="Hotel Asgard" width="120px"></a>
                    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                    </button>
                    <div class="collapse navbar-collapse justify-content-end" id="navbarSupportedContent">
                        <ul class="navbar-nav mb-2 mb-lg-0 text-center" style="font-size: 1.1rem;">
                            <li class="nav-item">
                                <a class="nav-link" href="{% url 'index' %}">Home</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="{% url 'rooms' %}">Rooms</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="{% url 'about' %}">About Us</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="{% url 'contact' %}">Contact</a>
                            </li>
                        </ul>
                    </div>
                </div>
            </nav>
        </header>
        <main class="main">
            {% block body %}

            {% endblock %}
        </main>

        <!-- Footer -->
        <footer class="custom-footer">
            <div class="row px-5 py-3 mb-2">
                <div class="col-md-6">
                    <h1>Book Now!</h1>
                    <ul class="list-unstyled">
                        <li><i class="fas fa-phone-alt"></i> +1600-555-6666</li>
                        <li><i class="far fa-envelope"></i> sales@hotelasgard.com</li>                        
                    </ul>
                    <ul class="list-unstyled d-flex custom-footer-social-icons">
                        <li class="pe-2"><i class="fab fa-facebook-square"></i></li>
                        <li class="px-2"><i class="fab fa-twitter-square"></i></li>
                        <li class="px-2"><i class="fab fa-linkedin"></i></li>
                        <li class="px-2"><i class="fab fa-pinterest-square"></i></li>
                        <li class="px-2"><i class="fab fa-instagram-square"></i></li>
                        <li class="ps-2"><i class="fab fa-flickr"></i></li>
                    </ul>
                </div>

                <div class="col-md-6">
                    <h1>Our Awards</h1>
                    <ul class="list-unstyled d-flex justify-content-around">
                        <li><img src="{% static 'asgard/img/award1.png' %}" alt="Forbes Award" width="80px"></li>
                        <li><img src="{% static 'asgard/img/award2.png' %}" alt="Royal Palace Award" width="80px"></li>
                        <li><img src="{% static 'asgard/img/award3.png' %}" alt="National Luxury Award" width="80px"></li>
                    </ul>
                </div>
            </div>

            <div class="px-5 py-3 d-flex justify-content-between" style="background-color: #e2e2e2;">
                <div class="text-secondary">
                    <a href="{% url 'index' %}" class="link-secondary">Home</a>
                    <span class="px-2">|</span>
                    <a href="{% url 'about' %}" class="link-secondary">About Us</a>
                    <span class="px-2">|</span>
                    <a href="{% url 'contact' %}" class="link-secondary">Contact</a> 
                </div>

                <div class="text-secondary">
                    Created by <a href="https://zoltanlederer.com" target="_blank" class="link-secondary">zoltanlederer.com</a>
                </div>
            </div>
        </footer>
    </div>


<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
<script src="https://js.stripe.com/v3/"></script>
<script src="{% static 'asgard/app.js' %}"></script>

</body>
</html>

asgard/templates/asgard/rooms.html
{% extends "asgard/layout.html" %}
{% load static %}
{% block body %}

<section class="">
    <div class="py-5 custom-rooms-header">
        <h1 class="m-0 px-3 text-center">Room Selection</h1>
    </div>
    
    <div class="m-5 d-flex flex-wrap custom-rooms-main">
    {% if rooms|length == 0 %}
        <div class="p-5 m-5 text-center alert alert-warning" role="alert">
            <h1>There are no available rooms between these dates</h1>
        </div>
    {% else %}
    
        {% for data in rooms %}
            <div class="mb-5 d-flex flex-column justify-content-between custom-rooms-box" style="width: 320px;">
                <div class="custom-rooms-box-header">
                    <a href="{% url 'room' data.id data.url_slug %}">
                        {% for i in data.media_set.all %}
                            <img src="{% static i.image_main %}" alt="{{ data.room_name }}" width="100%">
                        {% endfor %}                    
                    </a>
                </div>
                <div>
                    <h1 class="my-3 pb-3 text-center"><a href="{% url 'room' data.id data.url_slug %}">{{ data.room_name }}</a></h1>
                    <ul class="list-unstyled">
                        <li><i class="far fa-check-square"></i> <span class="fw-bold mx-3">Bed:</span><span class="fst-italic">{{ data.bed_type }}</span></li>
                        <li><i class="far fa-check-square"></i> <span class="fw-bold mx-3">Max People:</span><span class="fst-italic">{{ data.max_people }}</span></li>
                        <li><i class="far fa-check-square"></i> <span class="fw-bold mx-3">View:</span><span class="fst-italic">{{ data.view }}</span></li>
                        <li><i class="far fa-check-square"></i> <span class="fw-bold mx-3">Wifi:</span><span class="fst-italic">Yes</span></li>
                    </ul>
                    <h2 class="mb-4"><span class="fst-italic">Start From </span><span class="" style="color: #74b7d3;">${{ data.adult_price }} / Night</span></h2>
                    <a href="{% url 'room' data.id data.url_slug %}" >
                        <button>Check Details <i class="fas fa-long-arrow-alt-right"></i></button>
                    </a>
                </div>
            </div>
        {% endfor %}

    {% endif %}    
    </div>

</section>

{% endblock %}